#!/usr/bin/env python3
import argparse
import os
import pathlib
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
SERVER_DIR = ROOT / 'server'
if str(SERVER_DIR) not in sys.path:
    sys.path.insert(0, str(SERVER_DIR))

from app import create_app  # noqa: E402
from auth import _generate_automation_api_key  # noqa: E402
from models import User, UserAutomationKey, db  # noqa: E402


DEFAULT_API_BASE = 'http://127.0.0.1:5001'
DEFAULT_LABEL = 'Deployed Host Audit'


def default_env_file():
    return pathlib.Path(
        os.environ.get('LLM_CAMPAIGN_ENV_FILE')
        or (ROOT / 'automation' / 'llm_campaign.env')
    )


def resolve_user(*, username=None, user_id=None):
    if username:
        user = User.query.filter_by(username=username).first()
        if user is None:
            raise ValueError(f'No user found for username {username!r}')
        return user
    if user_id is not None:
        user = db.session.get(User, user_id)
        if user is None:
            raise ValueError(f'No user found for id {user_id}')
        return user
    raise ValueError('Pass --username or --user-id')


def write_env_file(path, api_base, api_key):
    env_path = pathlib.Path(path)
    env_path.parent.mkdir(parents=True, exist_ok=True)
    payload = (
        '# Generated by automation/ensure_host_audit_env.py\n'
        f'DND_API_BASE={api_base}\n'
        f'DND_OWNER_API_KEY={api_key}\n'
    )
    env_path.write_text(payload, encoding='utf-8')
    try:
        os.chmod(env_path, 0o600)
    except PermissionError:
        pass
    return env_path


def ensure_host_audit_env(*, username=None, user_id=None, label=DEFAULT_LABEL, env_file=None, api_base=DEFAULT_API_BASE):
    user = resolve_user(username=username, user_id=user_id)
    env_path = pathlib.Path(env_file) if env_file else default_env_file()

    existing = UserAutomationKey.query.filter_by(user_id=user.id, label=label).all()
    for row in existing:
        db.session.delete(row)
    db.session.flush()

    api_key, api_key_hash, api_key_prefix = _generate_automation_api_key()
    automation_key = UserAutomationKey(
        user_id=user.id,
        label=label,
        api_key_hash=api_key_hash,
        api_key_prefix=api_key_prefix,
    )
    db.session.add(automation_key)
    db.session.commit()

    write_env_file(env_path, api_base, api_key)
    return {
        'username': user.username,
        'user_id': user.id,
        'label': label,
        'env_file': str(env_path),
        'api_base': api_base,
        'api_key_prefix': api_key_prefix,
        'rotated_keys': len(existing),
    }


def parse_args():
    parser = argparse.ArgumentParser(
        description='Create or rotate a deploy-host automation key and write a CLI env file.',
    )
    parser.add_argument('--username', help='Owner username for the automation key')
    parser.add_argument('--user-id', type=int, help='Owner user id for the automation key')
    parser.add_argument('--label', default=DEFAULT_LABEL, help='Automation key label to rotate')
    parser.add_argument(
        '--env-file',
        default=str(default_env_file()),
        help='Destination env file path consumed by automation shell wrappers',
    )
    parser.add_argument(
        '--api-base',
        default=os.environ.get('DND_API_BASE', DEFAULT_API_BASE),
        help='API base URL written into the env file',
    )
    return parser.parse_args()


def main():
    args = parse_args()
    app = create_app()
    with app.app_context():
        result = ensure_host_audit_env(
            username=args.username,
            user_id=args.user_id,
            label=args.label,
            env_file=args.env_file,
            api_base=args.api_base,
        )
    print(result)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
